### ISSUE TITLE
配置 GitHub Action 使网站发布到 Github Pages 上

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/sig-envoy#3]
官网的内容我都改的差不多了，就差最后发布到 GitHub pages 上了，GitHub action 我配置过了，但是最后 hugo 编译的时候出错了，我实在没辙了 @helight 看下吧。

下面是 GitHub aciton 中的执行 hugo 的步骤包括，你也可以在 GitHub aciton 的任务里看到。

```
TypeError: Invalid PostCSS Plugin found: [0]
    at /home/runner/work/sig-envoy/sig-envoy/node_modules/postcss-load-plugins/lib/plugins.js:76:17
    at Array.forEach (<anonymous>)
    at plugins (/home/runner/work/sig-envoy/sig-envoy/node_modules/postcss-load-plugins/lib/plugins.js:65:8)
    at /home/runner/work/sig-envoy/sig-envoy/node_modules/postcss-load-config/index.js:64:18
    at async Promise.all (index 0)
Building sites … ERROR 2020/09/23 15:58:01 Transformation failed: exit status 1
Error: Error building site: logged 1 error(s)
Total in 1409 ms
Error: Process completed with exit code 255.
```

初步判断可能是因为在编译过程中下载的包有问题导致的。

**Comment by zyfjeff** [comment]
用最新的hugo版本，然后去除yarn相关的安装指令，直接用npm install就可以顺利build了。

**Comment by rootsongjc** [comment]
该问题已修复，现在网页已成功发布，见：https://cloudnative.to/sig-envoy/
